name: Automated Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Create and Process Test Data and show Output 
      run: |
        echo -e "type, client, tx, amount\ndeposit,1,1,1.0\ndeposit,2,2,2.0\ndeposit,1,3,2.0\nwithdrawal,1,4,1.5\nwithdrawal,2,5,3.0" > transactions.csv
        cat -A transactions.csv 
        cargo run -- transactions.csv > accounts.csv
        cat -A accounts.csv